//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firma.ViewResources.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulowane.
        /// </summary>
        public static string Anulowane {
            get {
                return ResourceManager.GetString("Anulowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Anuluj {
            get {
                return ResourceManager.GetString("Anuluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcin Siemiński.
        /// </summary>
        public static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string AutorLabel {
            get {
                return ResourceManager.GetString("AutorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutto.
        /// </summary>
        public static string Brutto {
            get {
                return ResourceManager.GetString("Brutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufor.
        /// </summary>
        public static string Bufor {
            get {
                return ResourceManager.GetString("Bufor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Cena {
            get {
                return ResourceManager.GetString("Cena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane Adresowe Kontrahenta.
        /// </summary>
        public static string DaneAdresoweKontrahenta {
            get {
                return ResourceManager.GetString("DaneAdresoweKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane ogólne.
        /// </summary>
        public static string DaneOgolne {
            get {
                return ResourceManager.GetString("DaneOgolne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane teleadresowe.
        /// </summary>
        public static string DaneTeleadresowe {
            get {
                return ResourceManager.GetString("DaneTeleadresowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sprzedaży.
        /// </summary>
        public static string DataSprzedazy {
            get {
                return ResourceManager.GetString("DataSprzedazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystawienia.
        /// </summary>
        public static string DataWystawienia {
            get {
                return ResourceManager.GetString("DataWystawienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zatrudnienia.
        /// </summary>
        public static string DataZatrudnienia {
            get {
                return ResourceManager.GetString("DataZatrudnienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daty i wartości.
        /// </summary>
        public static string DatyIWartosci {
            get {
                return ResourceManager.GetString("DatyIWartosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe.
        /// </summary>
        public static string Dodatkowe {
            get {
                return ResourceManager.GetString("Dodatkowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        public static string Dokument {
            get {
                return ResourceManager.GetString("Dokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugie imię.
        /// </summary>
        public static string DrugieImie {
            get {
                return ResourceManager.GetString("DrugieImie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drukuj.
        /// </summary>
        public static string Drukuj {
            get {
                return ResourceManager.GetString("Drukuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN (karta).
        /// </summary>
        public static string EAN {
            get {
                return ResourceManager.GetString("EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2.
        /// </summary>
        public static string EMail2 {
            get {
                return ResourceManager.GetString("EMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3.
        /// </summary>
        public static string EMail3 {
            get {
                return ResourceManager.GetString("EMail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail CC.
        /// </summary>
        public static string EMailCC {
            get {
                return ResourceManager.GetString("EMailCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura od.
        /// </summary>
        public static string FakturaOd {
            get {
                return ResourceManager.GetString("FakturaOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista faktur.
        /// </summary>
        public static string Faktury {
            get {
                return ResourceManager.GetString("Faktury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wszystkich faktur.
        /// </summary>
        public static string FakturyTooltip {
            get {
                return ResourceManager.GetString("FakturyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr zaawansowany.
        /// </summary>
        public static string FiltrZaawansowany {
            get {
                return ResourceManager.GetString("FiltrZaawansowany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiskalne.
        /// </summary>
        public static string Fiskalne {
            get {
                return ResourceManager.GetString("Fiskalne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma Płatności.
        /// </summary>
        public static string FormaPlatnosci {
            get {
                return ResourceManager.GetString("FormaPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FV marża.
        /// </summary>
        public static string FVMarza {
            get {
                return ResourceManager.GetString("FVMarza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gminy.
        /// </summary>
        public static string Gminy {
            get {
                return ResourceManager.GetString("Gminy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gminy lista.
        /// </summary>
        public static string GminyTooltip {
            get {
                return ResourceManager.GetString("GminyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        public static string Grupa {
            get {
                return ResourceManager.GetString("Grupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handlowe.
        /// </summary>
        public static string Handlowe {
            get {
                return ResourceManager.GetString("Handlowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        public static string Ilosc {
            get {
                return ResourceManager.GetString("Ilosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Imie {
            get {
                return ResourceManager.GetString("Imie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string ImieINazwisko {
            get {
                return ResourceManager.GetString("ImieINazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        public static string Inne {
            get {
                return ResourceManager.GetString("Inne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jm.
        /// </summary>
        public static string Jm {
            get {
                return ResourceManager.GetString("Jm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Kategoria {
            get {
                return ResourceManager.GetString("Kategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria Pomocnicza.
        /// </summary>
        public static string KategoriaPomocnicza {
            get {
                return ResourceManager.GetString("KategoriaPomocnicza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria prawa jazdy.
        /// </summary>
        public static string KategoriaPrawaJazdy {
            get {
                return ResourceManager.GetString("KategoriaPrawaJazdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient aktywny.
        /// </summary>
        public static string KlientAktywny {
            get {
                return ResourceManager.GetString("KlientAktywny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string KodPocztowy {
            get {
                return ResourceManager.GetString("KodPocztowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody CN.
        /// </summary>
        public static string KodyCN {
            get {
                return ResourceManager.GetString("KodyCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kontrahentów.
        /// </summary>
        public static string Kontrahenci {
            get {
                return ResourceManager.GetString("Kontrahenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wszystkich kontrahentów.
        /// </summary>
        public static string KontrahenciTooltip {
            get {
                return ResourceManager.GetString("KontrahenciTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent.
        /// </summary>
        public static string Kontrahent {
            get {
                return ResourceManager.GetString("Kontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korekty.
        /// </summary>
        public static string Korekty {
            get {
                return ResourceManager.GetString("Korekty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string Kraj {
            get {
                return ResourceManager.GetString("Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraje.
        /// </summary>
        public static string Kraje {
            get {
                return ResourceManager.GetString("Kraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraje.
        /// </summary>
        public static string KrajeTooltip {
            get {
                return ResourceManager.GetString("KrajeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj ISO.
        /// </summary>
        public static string KrajISO {
            get {
                return ResourceManager.GetString("KrajISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryterium wyszukiwania.
        /// </summary>
        public static string Kryterium {
            get {
                return ResourceManager.GetString("Kryterium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Kupiecki.
        /// </summary>
        public static string LimitKupiecki {
            get {
                return ResourceManager.GetString("LimitKupiecki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lp..
        /// </summary>
        public static string Lp {
            get {
                return ResourceManager.GetString("Lp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn.
        /// </summary>
        public static string Magazyn {
            get {
                return ResourceManager.GetString("Magazyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasta.
        /// </summary>
        public static string Miasta {
            get {
                return ResourceManager.GetString("Miasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string Miasto {
            get {
                return ResourceManager.GetString("Miasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Nazwa {
            get {
                return ResourceManager.GetString("Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Nazwisko {
            get {
                return ResourceManager.GetString("Nazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko rodowe.
        /// </summary>
        public static string NazwiskoRodowe {
            get {
                return ResourceManager.GetString("NazwiskoRodowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string Nie {
            get {
                return ResourceManager.GetString("Nie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string NIP {
            get {
                return ResourceManager.GetString("NIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa faktura.
        /// </summary>
        public static string NowaFaktura {
            get {
                return ResourceManager.GetString("NowaFaktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowej faktury.
        /// </summary>
        public static string NowaFakturaTooltip {
            get {
                return ResourceManager.GetString("NowaFakturaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy kontrahent.
        /// </summary>
        public static string NowyKontrahent {
            get {
                return ResourceManager.GetString("NowyKontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego kontrahenta.
        /// </summary>
        public static string NowyKontrahentTooltip {
            get {
                return ResourceManager.GetString("NowyKontrahentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy pracownik.
        /// </summary>
        public static string NowyPracownik {
            get {
                return ResourceManager.GetString("NowyPracownik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego pracownika.
        /// </summary>
        public static string NowyPracownikTooltip {
            get {
                return ResourceManager.GetString("NowyPracownikTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy towar.
        /// </summary>
        public static string NowyTowar {
            get {
                return ResourceManager.GetString("NowyTowar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego towaru.
        /// </summary>
        public static string NowyTowarTooltip {
            get {
                return ResourceManager.GetString("NowyTowarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr rachunku.
        /// </summary>
        public static string NrRachunku {
            get {
                return ResourceManager.GetString("NrRachunku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr uprawnien.
        /// </summary>
        public static string NrUprawnien {
            get {
                return ResourceManager.GetString("NrUprawnien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr zezwolenia.
        /// </summary>
        public static string NrZezwolenia {
            get {
                return ResourceManager.GetString("NrZezwolenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer dokumentu.
        /// </summary>
        public static string NumerDokumentu {
            get {
                return ResourceManager.GetString("NumerDokumentu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string Od {
            get {
                return ResourceManager.GetString("Od", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogólne.
        /// </summary>
        public static string Ogolne {
            get {
                return ResourceManager.GetString("Ogolne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba Kontaktowa.
        /// </summary>
        public static string OsobaKontaktowa {
            get {
                return ResourceManager.GetString("OsobaKontaktowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string Pesel {
            get {
                return ResourceManager.GetString("Pesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwotne.
        /// </summary>
        public static string Pierwotne {
            get {
                return ResourceManager.GetString("Pierwotne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płatność.
        /// </summary>
        public static string Platnosc {
            get {
                return ResourceManager.GetString("Platnosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płatności.
        /// </summary>
        public static string Platnosci {
            get {
                return ResourceManager.GetString("Platnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poczta.
        /// </summary>
        public static string Poczta {
            get {
                return ResourceManager.GetString("Poczta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowe dane kontrahenta.
        /// </summary>
        public static string PodstawoweDaneKontrahenta {
            get {
                return ResourceManager.GetString("PodstawoweDaneKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po terminie.
        /// </summary>
        public static string PoTerminie {
            get {
                return ResourceManager.GetString("PoTerminie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiaty.
        /// </summary>
        public static string Powiaty {
            get {
                return ResourceManager.GetString("Powiaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostaje.
        /// </summary>
        public static string Pozostaje {
            get {
                return ResourceManager.GetString("Pozostaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycje faktury.
        /// </summary>
        public static string PozycjeFaktury {
            get {
                return ResourceManager.GetString("PozycjeFaktury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista pracowników.
        /// </summary>
        public static string Pracownicy {
            get {
                return ResourceManager.GetString("Pracownicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wszystkich pracowników.
        /// </summary>
        public static string PracownicyTooltip {
            get {
                return ResourceManager.GetString("PracownicyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabat.
        /// </summary>
        public static string Rabat {
            get {
                return ResourceManager.GetString("Rabat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razem.
        /// </summary>
        public static string Razem {
            get {
                return ResourceManager.GetString("Razem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON.
        /// </summary>
        public static string Regon {
            get {
                return ResourceManager.GetString("Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string Rodzaj {
            get {
                return ResourceManager.GetString("Rodzaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj zatrudnienia.
        /// </summary>
        public static string RodzajZatrudnienia {
            get {
                return ResourceManager.GetString("RodzajZatrudnienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozliczone.
        /// </summary>
        public static string Rozliczone {
            get {
                return ResourceManager.GetString("Rozliczone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemat numeracji.
        /// </summary>
        public static string SchematNumeracji {
            get {
                return ResourceManager.GetString("SchematNumeracji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko.
        /// </summary>
        public static string Stanowisko {
            get {
                return ResourceManager.GetString("Stanowisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Szukaj {
            get {
                return ResourceManager.GetString("Szukaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukana fraza.
        /// </summary>
        public static string SzukanaFraza {
            get {
                return ResourceManager.GetString("SzukanaFraza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Tak {
            get {
                return ResourceManager.GetString("Tak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologie Produkcji Pieczątek.
        /// </summary>
        public static string TechnologieProdukcjiPieczatek {
            get {
                return ResourceManager.GetString("TechnologieProdukcjiPieczatek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Komórkowy.
        /// </summary>
        public static string TelefonKomorkowy {
            get {
                return ResourceManager.GetString("TelefonKomorkowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin Płatności.
        /// </summary>
        public static string TerminPlatnosci {
            get {
                return ResourceManager.GetString("TerminPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista towarów.
        /// </summary>
        public static string Towary {
            get {
                return ResourceManager.GetString("Towary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wszystkich towarów.
        /// </summary>
        public static string TowaryTooltip {
            get {
                return ResourceManager.GetString("TowaryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Ulica {
            get {
                return ResourceManager.GetString("Ulica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utw. WZ.
        /// </summary>
        public static string UtwWZ {
            get {
                return ResourceManager.GetString("UtwWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi.
        /// </summary>
        public static string Uwagi {
            get {
                return ResourceManager.GetString("Uwagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string Wartosc {
            get {
                return ResourceManager.GetString("Wartosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwa.
        /// </summary>
        public static string Wojewodztwa {
            get {
                return ResourceManager.GetString("Wojewodztwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo.
        /// </summary>
        public static string Wojewodztwo {
            get {
                return ResourceManager.GetString("Wojewodztwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        public static string Wyczyść {
            get {
                return ResourceManager.GetString("Wyczyść", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykształcenia.
        /// </summary>
        public static string Wyksztalcenia {
            get {
                return ResourceManager.GetString("Wyksztalcenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie kontrahenta.
        /// </summary>
        public static string WyszukiwanieKontrahenta {
            get {
                return ResourceManager.GetString("WyszukiwanieKontrahenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie pracownika.
        /// </summary>
        public static string WyszukiwaniePracownika {
            get {
                return ResourceManager.GetString("WyszukiwaniePracownika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadłużenie.
        /// </summary>
        public static string Zadluzenie {
            get {
                return ResourceManager.GetString("Zadluzenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaksięgowane.
        /// </summary>
        public static string Zaksiegowane {
            get {
                return ResourceManager.GetString("Zaksiegowane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaliczkowe.
        /// </summary>
        public static string Zaliczkowe {
            get {
                return ResourceManager.GetString("Zaliczkowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Zamknij {
            get {
                return ResourceManager.GetString("Zamknij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Zapisz {
            get {
                return ResourceManager.GetString("Zapisz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapłacono.
        /// </summary>
        public static string Zaplacono {
            get {
                return ResourceManager.GetString("Zaplacono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatrudnienie.
        /// </summary>
        public static string Zatrudnienie {
            get {
                return ResourceManager.GetString("Zatrudnienie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż / ukryj menu boczne.
        /// </summary>
        public static string ZmienWidocznoscMenu {
            get {
                return ResourceManager.GetString("ZmienWidocznoscMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z paragonem.
        /// </summary>
        public static string ZParagonem {
            get {
                return ResourceManager.GetString("ZParagonem", resourceCulture);
            }
        }
    }
}
